#!/usr/bin/env python3
"""Insert the static-sky SEFD panels at the end of the Antenna Monitor's
"All antennas" section.

The Antenna Monitor dashboard (uid yVY7CUOZk) is hand-maintained in the
Grafana UI, not generated by build_dashboard.py, so this edits the live
JSON in place: fetch, splice, POST with overwrite. It is idempotent --
re-running replaces the panels it added rather than stacking duplicates.
"""
from __future__ import annotations

import base64
import copy
import json
import os
import sys
import urllib.request

UID = "yVY7CUOZk"
URL = os.environ.get("GRAFANA_URL", "http://lxd110h20.pro.pvt:3000")
AUTH = os.environ["GRAFANA_AUTH"]

#: Stable ids so a re-run overwrites rather than duplicates.
PANEL_ID_SEFD = 9101
PANEL_ID_QUAL = 9102
PANEL_H = 9

#: The "All antennas" row is panel id 1 at y=0; its members run to y=18,
#: where the per-antenna row (id 2) begins. New panels go at that seam and
#: everything from there down shifts by PANEL_H.
INSERT_Y = 18


def _req(path: str, data: bytes | None = None):
    r = urllib.request.Request(URL + path, data=data)
    r.add_header("Authorization",
                 "Basic " + base64.b64encode(AUTH.encode()).decode())
    r.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(r, timeout=30) as f:
        return json.loads(f.read().decode())


SEFD_DESC = (
    "Per-antenna SEFD implied by the STATIC-SKY IMAGE path, published every "
    "~30 s by the sky monitor's frame loop and routed etcd /mon/sky/sefd -> "
    "influx sky_sefd.\n\n"
    "How it is derived: take the MAD noise of the static-sky-SUBTRACTED "
    "image, convert to mJy using a flux scale fitted against the NVSS "
    "sources detected in that same frame, then invert the radiometer "
    "equation\n\n"
    "    sigma_I = SEFD / sqrt(N_ant (N_ant-1) n_pol dnu tau)\n\n"
    "with N_ant=82, n_pol=2, dnu=181.9 MHz.\n\n"
    "READ IT AS AN UPPER BOUND, NOT AN ESTIMATE. Every imaging loss, "
    "calibration error and scrap of residual sky structure is absorbed into "
    "this one number, so it is an EFFECTIVE SYSTEM SEFD and is expected to "
    "sit above the true radiometric per-antenna SEFD. It is also a different "
    "measurement from the calibrator-based SEFD on the /sefds page (which "
    "fits a known-flux calibrator); the two are not interchangeable and will "
    "not agree.\n\n"
    "The dashed reference is SEFD_REFERENCE_JY = 7 kJy, the design figure the "
    "sky monitor compares against -- not a measurement.\n\n"
    "Gaps are deliberate: when static_sub_ready is false the instrumental "
    "baseline has not been subtracted, the image is structure-dominated and "
    "the flux-scale fit is meaningless, so nothing is published rather than a "
    "misleading zero. Check the companion panel before believing any single "
    "frame."
)

QUAL_DESC = (
    "Whether to believe the SEFD to the left, on a per-frame basis.\n\n"
    "n_flux_scale_sources is how many detected NVSS sources the flux scale "
    "was fitted against. The SEFD inherits their scatter, so a frame resting "
    "on a handful of sources is much softer than one resting on ~20. Treat "
    "single frames below ~5 sources with suspicion and read the trend "
    "instead.\n\n"
    "sigma_mjy is the measured image noise the SEFD is derived from, in mJy. "
    "It is the raw quantity; the SEFD is that number pushed through the "
    "radiometer equation, so the two move together and a jump in both at once "
    "is the sky/array actually changing rather than a fit artefact.\n\n"
    "If sigma_mjy is steady while the SEFD jumps, suspect the flux scale "
    "(source count, a bad NVSS match, astrometric drift) rather than the "
    "system temperature."
)


def make_panels() -> list[dict]:
    base = {
        "type": "graph", "datasource": "InfluxDB",
        "lines": True, "linewidth": 2, "fill": 0, "points": False,
        "pointradius": 2, "bars": False, "stack": False, "percentage": False,
        "steppedLine": False, "nullPointMode": "null", "renderer": "flot",
        "tooltip": {"shared": True, "sort": 0, "value_type": "individual"},
        "xaxis": {"buckets": None, "mode": "time", "name": None,
                  "show": True, "values": []},
        "legend": {"alignAsTable": True, "avg": True, "current": True,
                   "max": True, "min": True, "rightSide": False,
                   "show": True, "total": False, "values": True},
        "timeFrom": None, "timeShift": None, "thresholds": [], "links": [],
        "seriesOverrides": [],
    }
    sefd = copy.deepcopy(base)
    sefd.update({
        "id": PANEL_ID_SEFD,
        "title": "Static-sky implied SEFD (effective, upper bound)",
        "description": SEFD_DESC,
        "gridPos": {"h": PANEL_H, "w": 12, "x": 0, "y": INSERT_Y},
        "yaxes": [
            {"format": "short", "label": "kJy", "logBase": 1,
             "min": "0", "max": None, "show": True},
            {"format": "short", "label": None, "logBase": 1,
             "min": None, "max": None, "show": False},
        ],
        "targets": [
            {"refId": "A", "alias": "implied SEFD (kJy)", "rawQuery": True,
             "resultFormat": "time_series",
             "query": ('SELECT mean("sefd_implied_jy") / 1000 FROM "sky_sefd" '
                       'WHERE $timeFilter GROUP BY time($__interval) '
                       'fill(null)')},
            {"refId": "B", "alias": "design reference (kJy)", "rawQuery": True,
             "resultFormat": "time_series",
             "query": ('SELECT mean("ref_sefd_jy") / 1000 FROM "sky_sefd" '
                       'WHERE $timeFilter GROUP BY time($__interval) '
                       'fill(null)')},
        ],
        "seriesOverrides": [
            {"alias": "design reference (kJy)", "dashes": True,
             "linewidth": 1, "color": "#7f8c8d"},
        ],
    })
    qual = copy.deepcopy(base)
    qual.update({
        "id": PANEL_ID_QUAL,
        "title": "SEFD frame quality — flux-scale sources and image noise",
        "description": QUAL_DESC,
        "gridPos": {"h": PANEL_H, "w": 12, "x": 12, "y": INSERT_Y},
        "yaxes": [
            {"format": "short", "label": "NVSS sources in flux fit",
             "logBase": 1, "min": "0", "max": None, "show": True},
            {"format": "short", "label": "image noise (mJy)", "logBase": 1,
             "min": "0", "max": None, "show": True},
        ],
        "targets": [
            {"refId": "A", "alias": "flux-scale sources", "rawQuery": True,
             "resultFormat": "time_series",
             "query": ('SELECT mean("n_flux_scale_sources") FROM "sky_sefd" '
                       'WHERE $timeFilter GROUP BY time($__interval) '
                       'fill(null)')},
            {"refId": "B", "alias": "image noise (mJy)", "rawQuery": True,
             "resultFormat": "time_series",
             "query": ('SELECT mean("sigma_mjy") FROM "sky_sefd" '
                       'WHERE $timeFilter GROUP BY time($__interval) '
                       'fill(null)')},
        ],
        "seriesOverrides": [
            {"alias": "image noise (mJy)", "yaxis": 2, "color": "#e67e22"},
        ],
    })
    return [sefd, qual]


def main() -> int:
    doc = _req("/api/dashboards/uid/" + UID)
    db = doc["dashboard"]
    panels = db.get("panels", [])
    ours = {PANEL_ID_SEFD, PANEL_ID_QUAL}

    already = any(p.get("id") in ours for p in panels)
    kept = [p for p in panels if p.get("id") not in ours]

    if not already:
        # First insert: open a PANEL_H gap at the seam.
        for p in kept:
            gp = p.get("gridPos") or {}
            if int(gp.get("y", 0)) >= INSERT_Y:
                gp["y"] = int(gp["y"]) + PANEL_H
    else:
        print("  (panels already present — replacing in place, no reflow)")

    new = kept + make_panels()
    new.sort(key=lambda p: (int((p.get("gridPos") or {}).get("y", 0)),
                            int((p.get("gridPos") or {}).get("x", 0))))
    db["panels"] = new

    payload = json.dumps({
        "dashboard": db, "overwrite": True,
        "message": "Add static-sky implied SEFD to the All antennas section",
    }).encode()
    res = _req("/api/dashboards/db", data=payload)
    print("  Grafana:", {k: res.get(k) for k in ("status", "version", "uid")})
    print("  panels now:", len(new))
    for p in new:
        if p.get("id") in ours:
            gp = p["gridPos"]
            print("    +%-52s y=%s x=%s w=%s h=%s"
                  % (p["title"][:52], gp["y"], gp["x"], gp["w"], gp["h"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
